<a href="https://colab.research.google.com/github/kxtubh/Deep-Learning/blob/main/Loss_Cost_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
y_predicted = np.array([0,1,0,1,1,1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5,0.6,0.3,0.2,0.1,0.9])

In [57]:
y_predicted = np.random.randint(0, 2, 10)

In [88]:
y_true = np.random.uniform(0, 1, 10)

In [89]:
y_predicted

array([1, 0, 0, 1, 1, 0, 0, 1, 1, 0])

In [90]:
y_true

array([0.69399922, 0.47515505, 0.18529837, 0.18154252, 0.07580292,
       0.04719669, 0.86435625, 0.86265962, 0.81906112, 0.95346937])

In [91]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [92]:
mae(y_predicted, y_true)

Total error is: 4.89241032730793
Mean absolute error is: 0.489241032730793


np.float64(0.489241032730793)

In [93]:
np.abs(y_predicted-y_true)

array([0.30600078, 0.47515505, 0.18529837, 0.81845748, 0.92419708,
       0.04719669, 0.86435625, 0.13734038, 0.18093888, 0.95346937])

In [94]:
np.mean(np.abs(y_predicted-y_true))

np.float64(0.4892410327307931)

In [96]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [97]:
mae_np(y_predicted, y_true)

np.float64(0.4892410327307931)

In [98]:
np.log([0])

<ipython-input-98-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [99]:
epsilon = 1e-15

In [100]:
np.log([1e-15])

array([-34.53877639])

In [101]:
y_predicted

array([1, 0, 0, 1, 1, 0, 0, 1, 1, 0])

In [102]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[np.int64(1),
 1e-15,
 1e-15,
 np.int64(1),
 np.int64(1),
 1e-15,
 1e-15,
 np.int64(1),
 np.int64(1),
 1e-15]

In [103]:
1-epsilon

0.999999999999999

In [104]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999,
 1e-15,
 1e-15,
 0.999999999999999,
 0.999999999999999,
 1e-15,
 1e-15,
 0.999999999999999,
 0.999999999999999,
 1e-15]

In [105]:
y_predicted_new = np.array(y_predicted_new)

In [106]:
np.log(y_predicted_new)

array([-9.99200722e-16, -3.45387764e+01, -3.45387764e+01, -9.99200722e-16,
       -9.99200722e-16, -3.45387764e+01, -3.45387764e+01, -9.99200722e-16,
       -9.99200722e-16, -3.45387764e+01])

In [107]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(16.897975892185496)

In [108]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [109]:
log_loss(y_true, y_predicted)

np.float64(16.897975892185496)

In [110]:
#Without Numpy [Hardcode]
def mse(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += (yp - yt) ** 2
    mse_value = total_error / len(y_predicted)
    return mse_value

print(mse(y_predicted, y_true))

0.35878015235060734


In [111]:
#With Numpy
def mse_np(y_predicted, y_true):
    return np.mean((y_predicted - y_true) ** 2)

print(mse_np(y_predicted, y_true))

0.35878015235060734
