<a href="https://colab.research.google.com/github/kxtubh/Deep-Learning/blob/main/Hardcoded/Loss_Cost_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
y_predicted = np.random.randint(0, 2, 10)

In [3]:
y_true = np.random.uniform(0, 1, 10)

In [4]:
y_predicted

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 0])

In [5]:
y_true

array([0.15787098, 0.26973053, 0.79440259, 0.98684796, 0.87284939,
       0.79134042, 0.1104726 , 0.50049287, 0.83588207, 0.09129846])

In [6]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [7]:
mae(y_predicted, y_true)

Total error is: 3.7980980864942464
Mean absolute error is: 0.37980980864942465


np.float64(0.37980980864942465)

In [8]:
np.abs(y_predicted-y_true)

array([0.15787098, 0.26973053, 0.79440259, 0.01315204, 0.12715061,
       0.79134042, 0.8895274 , 0.49950713, 0.16411793, 0.09129846])

In [9]:
np.mean(np.abs(y_predicted-y_true))

np.float64(0.3798098086494246)

In [10]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [11]:
mae_np(y_predicted, y_true)

np.float64(0.3798098086494246)

In [12]:
np.log([0])

<ipython-input-12-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [13]:
epsilon = 1e-15

In [14]:
np.log([1e-15])

array([-34.53877639])

In [15]:
y_predicted

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 0])

In [16]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1e-15,
 1e-15,
 1e-15,
 np.int64(1),
 np.int64(1),
 1e-15,
 np.int64(1),
 np.int64(1),
 np.int64(1),
 1e-15]

In [17]:
1-epsilon

0.999999999999999

In [18]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[1e-15,
 1e-15,
 1e-15,
 0.999999999999999,
 0.999999999999999,
 1e-15,
 0.999999999999999,
 0.999999999999999,
 0.999999999999999,
 1e-15]

In [19]:
y_predicted_new = np.array(y_predicted_new)

In [20]:
np.log(y_predicted_new)

array([-3.45387764e+01, -3.45387764e+01, -3.45387764e+01, -9.99200722e-16,
       -9.99200722e-16, -3.45387764e+01, -9.99200722e-16, -9.99200722e-16,
       -9.99200722e-16, -3.45387764e+01])

In [21]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(13.118301461772026)

In [22]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [23]:
log_loss(y_true, y_predicted)

np.float64(13.118301461772026)

In [24]:
#Without Numpy [Hardcode]
def mse(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += (yp - yt) ** 2
    mse_value = total_error / len(y_predicted)
    return mse_value

print(mse(y_predicted, y_true))

0.24473496551019652


In [25]:
#With Numpy
def mse_np(y_predicted, y_true):
    return np.mean((y_predicted - y_true) ** 2)

print(mse_np(y_predicted, y_true))

0.24473496551019652
